language: ruby
cache: bundler
dist: trusty
sudo: false

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

before_install:
  - gem install bundler

gemfile: ci.gemfile

env:
  - CHEF_VERSION="master"
  - CHEF_VERSION="~> 12.0"

matrix:
  exclude:
  - rvm: 2.2.7
    env: CHEF_VERSION="master"
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master
